### ISSUE TITLE
Switch the Ruby vscode extension to Shopify's Ruby LSP

### ISSUE THREAD

**Issue by wJoenn** [lewagon/setup#455] opened 2024-02-20 21:40 UTC
Even the `Ruby` extension marked itself as deprecated and redirect to `Ruby LSP`
We've been using it at work for months and haven't really stumbled on much bugs so far (not more than we already have with the deprecated extension at least). I think it's safe to make the change by now

![image](https://github.com/lewagon/setup/assets/75388869/171056fd-a7cf-41e0-86f6-6ffae2135907)

**Comment by v-natalia** [comment] 2024-02-27 07:50
Duplicate of https://github.com/lewagon/teachers/issues/1780

**Comment by ajdubovoy** [comment] 2024-05-31 16:04
Closing as duplicate

**Closed by ajdubovoy** 2024-05-31 16:04 UTC
