### ISSUE TITLE
Ruby VS extension is deprecated

### ISSUE THREAD

**Issue by v-natalia** [lewagon/setup#449] opened 2023-11-30 13:23 UTC
Section https://github.com/lewagon/setup/blob/master/windows.md#vs-code-extensions

`code --install-extension rebornix.ruby`
Extension Ruby has been deprecated, what is the official suggestion from Le Wagon? Ruby LSP?

https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp 
Please update the guide :)

**Comment by ajdubovoy** [comment] 2024-01-19 14:52
Duplicate of https://github.com/lewagon/teachers/issues/1780

**Closed by ajdubovoy** 2024-01-19 14:52 UTC
